config/routes.rb
Rails.application.routes.draw do
  get 'job/add'

  get 'job/list'

  resources :resumes do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  member do
  	get 'viewed'
  end
end
end

app/models/application.rb
class Application < ApplicationRecord
	belongs_to :resume
	belongs_to :employer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cover_letter.rb
class CoverLetter < ApplicationRecord
end

app/models/employer.rb
class Employer < ApplicationRecord
	has_many :applications
end

app/models/job.rb
class Job < ApplicationRecord
	attr_accessor :company_name, :end_date, :start_date, :work_summary, :resume_id
	belongs_to :resume
end

app/models/resume.rb
class Resume < ApplicationRecord
	before_save :do_logging

	def do_logging
		puts "Saving Object"
	end

	has_many :view_histories
	has_many :jobs
	has_one :cover_letter
	has_and_belongs_to_many :employers
	has_many :applications
	has_many :employers, through: :applications
end

app/models/view_history.rb
class ViewHistory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/job_controller.rb
class JobController < ApplicationController
  def add
  end

  def list
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :check_for_top_secret, :set_resume, only: [:show, :edit, :update, :destroy]
   

  def check_for_top_secret
    p "**********" * 10 
    p params[:id]
    p params[:id] && params[:id].to_i > 500
    render :inline => "Not authorized", :status => 403 if params[:id] && params[:id].to_i > 500
  end

  def viewed
    resume = Resume.find(params[:id])
    @views = resume.view_histories
  end

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    vh = ViewHistory.new(:time_viewed => Time.now, :ip => request.remote_ip, :resume_id => @resume.id)
    vh.save
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:name, :phone, :email, :street, :city, :state, :zip, :summary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/job/add.html.erb
<h1>Job#add</h1>
<p>Find me in app/views/job/add.html.erb</p>

app/views/job/list.html.erb
<h1>Job#list</h1>
<p>Find me in app/views/job/list.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resumeappp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resumes/_form.html.erb
<%= form_with(model: resume, local: true) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :resume_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :resume_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :resume_email %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :resume_street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :resume_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :resume_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :resume_zip %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary, id: :resume_summary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td><%= resume.phone %></td>
        <td><%= resume.email %></td>
        <td><%= resume.street %></td>
        <td><%= resume.city %></td>
        <td><%= resume.state %></td>
        <td><%= resume.zip %></td>
        <td><%= resume.summary %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<% if @resume != nil %>

<strong>Name:</strong>
  <%= @resume.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resume.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resume.email %>
</p>

<p>
  <strong>Street:</strong>
  <%= @resume.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @resume.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @resume.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @resume.zip %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @resume.summary %>
</p>


<%= link_to 'Edit', edit_resume_path(@resume) %> |
<% end %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/viewed.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Views</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>IP</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @views.each do |view| %>
      <tr>
        <td><%= view.time_viewed %></td>
        <td><%= view.ip %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>